### ISSUE TITLE
Plugin with id 'com.decathlon.phraseapp' not found.

### ISSUE THREAD

**Issue by pstambrecht** [Decathlon/gradle-plugin-phraseapp#8]
Hi,
thanks for this plugin. I'm trying to use it but I'm getting `Plugin with id 'com.decathlon.phraseapp' not found.` exception.

**My configuration**
Project root directory build.gradle.kts:
```
.
.
.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath(gradleDependencies.plugins.androidGradle)
        classpath(gradleDependencies.plugins.kotlinGradle)
        classpath("com.decathlon.phrase:phrase-gradle-plugin:0.0.1")
    }


}
.
.
.
```

Android library build.gradle.kts
```
plugins {
    id("com.android.library")
    id("kotlin-android")
    id("com.decathlon.phraseapp")
}
```

I'll be glad for any advice or sample code/app. Thanks.

**Comment by pstambrecht** [comment]
Snapshot version works fine. Can you please release it as 0.0.2?

**Comment by GerardPaligot** [comment]
Thanks for your issue @pstambrecht!

Yes, like you said, the current version of the project was only released on the SNAPSHOT version. We planned to release the project after some internal tests and everything is okay now.

We have some difficulties to publish the version on Maven Central but the version 1.0.0-beta01 should be available on Maven Central soon. Don't hesitate to re-open this issue if it is necessary or create a new issue if you find any bug with the beta version!

**Comment by pstambrecht** [comment]
Thanks for the answer 👍
